/*
 * HELLDIVERS 2 loadout catalogue
 * Data boundary: 2026-08-13. Model codes are retained verbatim for verification.
 * `released: false` records are visible but can never enter the random pool.
 */
const WARBONDS = [
  ['base','基础军备 / 爱国行政中心','Base Arsenal / PAC','2024-02-08',true,'standard'],
  ['mobilize','绝地潜兵动员！','Helldivers Mobilize!','2024-02-08',true,'standard'],
  ['steeled','铁血老兵','Steeled Veterans','2024-02-08',true,'premium'],
  ['cutting','尖端科技','Cutting Edge','2024-03-14',true,'premium'],
  ['detonation','民主爆破','Democratic Detonation','2024-04-11',true,'premium'],
  ['polar','极地爱国者','Polar Patriots','2024-05-09',true,'premium'],
  ['viper','毒蛇突击队','Viper Commandos','2024-06-13',true,'premium'],
  ['flame','自由之火','Freedom’s Flame','2024-08-08',true,'premium'],
  ['chemical','化学制剂','Chemical Agents','2024-09-19',true,'premium'],
  ['truth','真理执法者','Truth Enforcers','2024-10-31',true,'premium'],
  ['urban','都市传奇','Urban Legends','2024-12-12',true,'premium'],
  ['servants','自由之仆','Servants of Freedom','2025-02-06',true,'premium'],
  ['justice','边境正义','Borderline Justice','2025-03-20',true,'premium'],
  ['ceremony','典礼大师','Masters of Ceremony','2025-05-15',true,'premium'],
  ['law','法律之力','Force of Law','2025-06-12',true,'premium'],
  ['control','对照组','Control Group','2025-07-17',true,'premium'],
  ['dust','沙尘恶魔','Dust Devils','2025-09-04',true,'premium'],
  ['odst','服从民主支援部队','Obedient Democracy Support Troopers','2025-08-26',true,'legendary'],
  ['python','巨蟒突击队','Python Commandos','2025-12-02',true,'premium'],
  ['killzone','正义亡魂','Righteous Revenants','2025-12-18',true,'legendary'],
  ['redacted','绝密团','Redacted Regiment','2026-01-20',true,'premium'],
  ['siege','攻城破阵者','Siege Breakers','2026-02-03',true,'premium'],
  ['entrenched','战壕之师','Entrenched Division','2026-03-17',true,'premium'],
  ['exo','外骨骼专家','Exo Experts','2026-04-28',true,'premium'],
  ['warhammer','城主信条','Castellan’s Creed','2026-08-12',true,'legendary']
].map(([id,zh,en,date,released,tier])=>({id,zh,en,date,released,tier}));

const RAW_GEAR = [
  // Primary weapons
  ['primary','AR-23“解放者”突击步枪','AR-23 Liberator','base'],
  ['primary','AR-23P“解放者”穿透型','AR-23P Liberator Penetrator','mobilize'],
  ['primary','AR-23C“解放者”震荡型','AR-23C Liberator Concussive','steeled'],
  ['primary','AR-23A“解放者”卡宾型','AR-23A Liberator Carbine','viper'],
  ['primary','AR-61“嫩化者”突击步枪','AR-61 Tenderizer','polar'],
  ['primary','AR-32“安抚者”突击步枪','AR-32 Pacifier','law'],
  ['primary','AR-2“郊狼”突击步枪','AR-2 Coyote','dust'],
  ['primary','AR-59“抑制者”突击步枪','AR-59 Suppressor','redacted'],
  ['primary','AR/GL-21“一石二鸟”突击步枪','AR/GL-21 One-Two','python'],
  ['primary','BR-14“裁决者”战斗步枪','BR-14 Adjudicator','detonation'],
  ['primary','MA5C 突击步枪','MA5C Assault Rifle','odst'],
  ['primary','R-63“勤勉”神射手步枪','R-63 Diligence','mobilize'],
  ['primary','R-63CS“勤勉”反狙击型','R-63CS Diligence Counter Sniper','mobilize'],
  ['primary','R-36“喷发者”爆弹步枪','R-36 Eruptor','detonation'],
  ['primary','R-2124“宪法”步枪','R-2124 Constitution','base'],
  ['primary','R-6“神射手”步枪','R-6 Deadeye','justice'],
  ['primary','R-2“修正案”步枪','R-2 Amendment','ceremony'],
  ['primary','R-72“审查者”步枪','R-72 Censor','redacted'],
  ['primary','VG-70“变量”步枪','VG-70 Variable','control'],
  ['primary','SMG-37“防卫者”冲锋枪','SMG-37 Defender','mobilize'],
  ['primary','SMG-72“猛击者”冲锋枪','SMG-72 Pummeler','polar'],
  ['primary','SMG-32“斥责者”冲锋枪','SMG-32 Reprimand','truth'],
  ['primary','MP-98“骑士”冲锋枪','MP-98 Knight','base'],
  ['primary','M7S 消音冲锋枪','M7S SMG','odst'],
  ['primary','StA-11 冲锋枪','StA-11 SMG','killzone'],
  ['primary','StA-52 突击步枪','StA-52 Assault Rifle','killzone'],
  ['primary','SMG-203“英勇者”冲锋枪','SMG-203 Gallant','exo'],
  ['primary','SG-8“惩罚者”霰弹枪','SG-8 Punisher','mobilize'],
  ['primary','SG-8S“猛击者”独头弹霰弹枪','SG-8S Slugger','mobilize'],
  ['primary','SG-8P“惩罚者”等离子型','SG-8P Punisher Plasma','cutting'],
  ['primary','SG-225“破裂者”霰弹枪','SG-225 Breaker','mobilize'],
  ['primary','SG-225IE“破裂者”燃烧型','SG-225IE Breaker Incendiary','steeled'],
  ['primary','SG-225SP“破裂者”喷射祈祷型','SG-225SP Breaker Spray & Pray','mobilize'],
  ['primary','SG-451“野炊”霰弹枪','SG-451 Cookout','flame'],
  ['primary','SG-20“喝止”霰弹枪','SG-20 Halt','truth'],
  ['primary','M90A 霰弹枪','M90A Shotgun','odst'],
  ['primary','DBS-2“双重自由”霰弹枪','DBS-2 Double Freedom','base'],
  ['primary','SMG/FLAM-34“爆燃者”','SMG/FLAM-34 Stoker','entrenched'],
  ['primary','SG-97“清扫者”霰弹枪','SG-97 Sweeper','entrenched'],
  ['primary','CB-9 爆炸十字弩','CB-9 Exploding Crossbow','detonation'],
  ['primary','JAR-5“主宰者”爆弹枪','JAR-5 Dominator','steeled'],
  ['primary','FLAM-66“火炬手”火焰枪','FLAM-66 Torcher','flame'],
  ['primary','LAS-5“镰刀”激光步枪','LAS-5 Scythe','mobilize'],
  ['primary','LAS-16“镰刃”激光步枪','LAS-16 Sickle','cutting'],
  ['primary','LAS-17“双刃镰”激光步枪','LAS-17 Double-Edge Sickle','servants'],
  ['primary','LAS-13“三叉戟”激光霰弹枪','LAS-13 Trident','siege'],
  ['primary','ARC-12“雷霆”电弧霰弹枪','ARC-12 Blitzer','cutting'],
  ['primary','PLAS-1“焦土”等离子步枪','PLAS-1 Scorcher','mobilize'],
  ['primary','PLAS-101“净化者”','PLAS-101 Purifier','polar'],
  ['primary','PLAS-39 加速步枪','PLAS-39 Accelerator Rifle','killzone'],
  ['primary','R/40-K 热熔神射手步枪','R/40-K Hot-Shot Marksman Rifle','warhammer'],

  // Secondary weapons and melee
  ['secondary','P-2“和平缔造者”手枪','P-2 Peacemaker','base'],
  ['secondary','P-19“救世主”自动手枪','P-19 Redeemer','mobilize'],
  ['secondary','P-4“参议员”左轮手枪','P-4 Senator','steeled'],
  ['secondary','LAS-7“匕首”激光手枪','LAS-7 Dagger','cutting'],
  ['secondary','GP-31 榴弹手枪','GP-31 Grenade Pistol','detonation'],
  ['secondary','P-113“裁决”手枪','P-113 Verdict','polar'],
  ['secondary','SG-22“灌木猎枪”','SG-22 Bushwhacker','viper'],
  ['secondary','P-72“脆化者”火焰手枪','P-72 Crisper','flame'],
  ['secondary','P-11 治疗剂手枪','P-11 Stim Pistol','chemical'],
  ['secondary','PLAS-15“忠诚者”','PLAS-15 Loyalist','truth'],
  ['secondary','GP-20“最后通牒”','GP-20 Ultimatum','servants'],
  ['secondary','LAS-58“猛禽”激光手枪','LAS-58 Talon','justice'],
  ['secondary','P-35“再教育者”手枪','P-35 Re-Educator','redacted'],
  ['secondary','P-69“否决”手枪','P-69 Veto','entrenched'],
  ['secondary','P-33 导弹手枪','P-33 Missile Pistol','exo'],
  ['secondary','M6C/SOCOM 手枪','M6C/SOCOM Pistol','odst'],
  ['secondary','P-92“授权令”手枪','P-92 Warrant','base'],
  ['secondary','CQC-2 军刀','CQC-2 Saber','ceremony'],
  ['secondary','CQC-5 战斧','CQC-5 Combat Hatchet','base'],
  ['secondary','CQC-42 大砍刀','CQC-42 Machete','dust'],
  ['secondary','CQC-30 电击警棍','CQC-30 Stun Baton','urban'],
  ['secondary','CQC-73 挖掘工具','CQC-73 Entrenchment Tool','entrenched'],
  ['secondary','P/40-K 爆弹手枪','P/40-K Bolt Pistol','warhammer'],

  // Throwables
  ['throwable','G-12 高爆手榴弹','G-12 High Explosive','base'],
  ['throwable','G-6 破片手榴弹','G-6 Frag','mobilize'],
  ['throwable','G-16 冲击手榴弹','G-16 Impact','mobilize'],
  ['throwable','G-3 烟雾弹','G-3 Smoke','mobilize'],
  ['throwable','G-10 燃烧弹','G-10 Incendiary','steeled'],
  ['throwable','G-23 眩晕弹','G-23 Stun','cutting'],
  ['throwable','G-123 铝热弹','G-123 Thermite','detonation'],
  ['throwable','G-13 燃烧冲击弹','G-13 Incendiary Impact','polar'],
  ['throwable','K-2 飞刀','K-2 Throwing Knife','viper'],
  ['throwable','G-4 毒气弹','G-4 Gas','chemical'],
  ['throwable','G-50“探索者”自爆无人机','G-50 Seeker','servants'],
  ['throwable','TED-63 炸药束','TED-63 Dynamite','justice'],
  ['throwable','G-142 烟火弹','G-142 Pyrotech','ceremony'],
  ['throwable','G-109“海胆”刺钉弹','G-109 Urchin','law'],
  ['throwable','G-31 电弧手榴弹','G-31 Arc','control'],
  ['throwable','G-7“菠萝”手榴弹','G-7 Pineapple','dust'],
  ['throwable','TM-1 诱饵地雷','TM-1 Lure Mine','redacted'],
  ['throwable','G/SH-39 投掷护盾','G/SH-39 Shield','siege'],
  ['throwable','G-48 巨型手榴弹','G-48 Giga Grenade','entrenched'],
  ['throwable','G/40-K 热熔地雷','G/40-K Melta Mine','warhammer'],
  ['throwable','G-89 烟幕弹','G-89 Smokescreen','base'],

  // Orbital and Eagle stratagems
  ['stratagem','轨道精准打击','Orbital Precision Strike','base','offensive'],
  ['stratagem','轨道加特林弹幕','Orbital Gatling Barrage','base','offensive'],
  ['stratagem','轨道空爆打击','Orbital Airburst Strike','base','offensive'],
  ['stratagem','轨道 120 毫米高爆弹幕','Orbital 120mm HE Barrage','base','offensive'],
  ['stratagem','轨道 380 毫米高爆弹幕','Orbital 380mm HE Barrage','base','offensive'],
  ['stratagem','轨道游走弹幕','Orbital Walking Barrage','base','offensive'],
  ['stratagem','轨道激光','Orbital Laser','base','offensive'],
  ['stratagem','轨道凝固汽油弹幕','Orbital Napalm Barrage','base','offensive'],
  ['stratagem','轨道磁轨炮打击','Orbital Railcannon Strike','base','offensive'],
  ['stratagem','轨道毒气打击','Orbital Gas Strike','base','offensive'],
  ['stratagem','轨道电磁脉冲打击','Orbital EMS Strike','base','offensive'],
  ['stratagem','轨道烟雾打击','Orbital Smoke Strike','base','offensive'],
  ['stratagem','飞鹰机枪扫射','Eagle Strafing Run','base','offensive'],
  ['stratagem','飞鹰空袭','Eagle Airstrike','base','offensive'],
  ['stratagem','飞鹰集束炸弹','Eagle Cluster Bomb','base','offensive'],
  ['stratagem','飞鹰凝固汽油空袭','Eagle Napalm Airstrike','base','offensive'],
  ['stratagem','飞鹰烟雾打击','Eagle Smoke Strike','base','offensive'],
  ['stratagem','飞鹰 110 毫米火箭巢','Eagle 110mm Rocket Pods','base','offensive'],
  ['stratagem','飞鹰 500 千克炸弹','Eagle 500kg Bomb','base','offensive'],

  // Defensive stratagems
  ['stratagem','反步兵雷区','Anti-Personnel Minefield','base','defensive'],
  ['stratagem','燃烧地雷','Incendiary Mines','base','defensive'],
  ['stratagem','反坦克地雷','Anti-Tank Mines','base','defensive'],
  ['stratagem','毒气地雷','Gas Mines','chemical','defensive'],
  ['stratagem','A/MG-43 机枪岗哨','A/MG-43 Machine Gun Sentry','base','defensive'],
  ['stratagem','A/G-16 加特林岗哨','A/G-16 Gatling Sentry','base','defensive'],
  ['stratagem','A/AC-8 自动炮岗哨','A/AC-8 Autocannon Sentry','base','defensive'],
  ['stratagem','A/MLS-4X 火箭岗哨','A/MLS-4X Rocket Sentry','base','defensive'],
  ['stratagem','A/M-12 迫击炮岗哨','A/M-12 Mortar Sentry','base','defensive'],
  ['stratagem','A/M-23 电磁脉冲迫击炮岗哨','A/M-23 EMS Mortar Sentry','base','defensive'],
  ['stratagem','A/FLAM-40 火焰岗哨','A/FLAM-40 Flame Sentry','urban','defensive'],
  ['stratagem','A/LAS-98 激光岗哨','A/LAS-98 Laser Sentry','base','defensive'],
  ['stratagem','A/GM-17 毒气迫击炮岗哨','A/GM-17 Gas Mortar Sentry','entrenched','defensive'],
  ['stratagem','E/MG-101 重机枪阵地','E/MG-101 HMG Emplacement','base','defensive'],
  ['stratagem','E/AT-12 反坦克炮台','E/AT-12 Anti-Tank Emplacement','urban','defensive'],
  ['stratagem','E/GL-21 掷弹兵胸墙','E/GL-21 Grenadier Battlement','base','defensive'],
  ['stratagem','FX-12 护盾生成中继器','FX-12 Shield Generator Relay','base','defensive'],
  ['stratagem','A/ARC-3 特斯拉塔','A/ARC-3 Tesla Tower','base','defensive'],

  // Support weapons
  ['stratagem','MG-43 机枪','MG-43 Machine Gun','base','support'],
  ['stratagem','M-105 勤务机枪','M-105 Stalwart','base','support'],
  ['stratagem','MG-206 重机枪','MG-206 Heavy Machine Gun','base','support'],
  ['stratagem','APW-1 反器材步枪','APW-1 Anti-Materiel Rifle','base','support'],
  ['stratagem','RS-422 轨道炮','RS-422 Railgun','base','support'],
  ['stratagem','AC-8 自动炮','AC-8 Autocannon','base','support backpack'],
  ['stratagem','GL-21 榴弹发射器','GL-21 Grenade Launcher','base','support'],
  ['stratagem','FLAM-40 火焰喷射器','FLAM-40 Flamethrower','base','support'],
  ['stratagem','LAS-98 激光大炮','LAS-98 Laser Cannon','base','support'],
  ['stratagem','LAS-99 类星体加农炮','LAS-99 Quasar Cannon','base','support'],
  ['stratagem','ARC-3 电弧发射器','ARC-3 Arc Thrower','base','support'],
  ['stratagem','EAT-17 消耗性反坦克武器','EAT-17 Expendable Anti-Tank','base','support'],
  ['stratagem','GR-8 无后坐力步枪','GR-8 Recoilless Rifle','base','support backpack'],
  ['stratagem','FAF-14“长矛”发射器','FAF-14 Spear','base','support backpack'],
  ['stratagem','MLS-4X“突击兵”火箭发射器','MLS-4X Commando','base','support'],
  ['stratagem','RL-77 空爆火箭发射器','RL-77 Airburst Rocket Launcher','base','support backpack'],
  ['stratagem','StA-X3“黄蜂”发射器','StA-X3 W.A.S.P. Launcher','base','support backpack'],
  ['stratagem','TX-41“灭菌器”','TX-41 Sterilizer','chemical','support'],
  ['stratagem','S-11 鱼叉枪','S-11 Speargun','dust','support'],
  ['stratagem','EAT-700 消耗性凝固汽油弹','EAT-700 Expendable Napalm','dust','support'],
  ['stratagem','M-1000“极限机枪”','M-1000 Maxigun','python','support backpack'],
  ['stratagem','EAT-411“夷平者”','EAT-411 Leveller','siege','support'],
  ['stratagem','GL-28 带式榴弹发射器','GL-28 Belt-Fed Grenade Launcher','siege','support backpack'],
  ['stratagem','B/FLAM-80“火葬者”','B/FLAM-80 Cremator','entrenched','support backpack'],
  ['stratagem','MGX-42“弹雨”','MGX-42 Bullet Storm','exo','support'],
  ['stratagem','40-K 热熔枪','40-K Meltagun','warhammer','support'],

  // Backpacks, vehicles and utility stratagems
  ['stratagem','B-1 补给背包','B-1 Supply Pack','base','backpack'],
  ['stratagem','SH-20 弹道护盾背包','SH-20 Ballistic Shield Backpack','base','backpack'],
  ['stratagem','SH-32 护盾生成背包','SH-32 Shield Generator Pack','base','backpack'],
  ['stratagem','LIFT-850 跳跃背包','LIFT-850 Jump Pack','base','backpack'],
  ['stratagem','LIFT-860 悬浮背包','LIFT-860 Hover Pack','control','backpack'],
  ['stratagem','LIFT-182 曲速背包','LIFT-182 Warp Pack','base','backpack'],
  ['stratagem','AX/AR-23“护卫犬”','AX/AR-23 Guard Dog','base','backpack'],
  ['stratagem','AX/LAS-5“巡游犬”','AX/LAS-5 Rover','base','backpack'],
  ['stratagem','AX/TX-13“毒息犬”','AX/TX-13 Dog Breath','chemical','backpack'],
  ['stratagem','AX/ARC-3“K-9”电弧犬','AX/ARC-3 K-9','python','backpack'],
  ['stratagem','AX/FLAM-75“热狗”','AX/FLAM-75 Hot Dog','base','backpack'],
  ['stratagem','SH-51 定向护盾','SH-51 Directional Shield','urban','backpack'],
  ['stratagem','B/MD-1 C4 背包','B/MD-1 C4 Pack','redacted','backpack'],
  ['stratagem','B-100 便携式地狱火炸弹','B-100 Portable Hellbomb','servants','backpack'],
  ['stratagem','EXO-45“爱国者”外骨骼装甲','EXO-45 Patriot Exosuit','base','vehicle'],
  ['stratagem','EXO-49“解放者”外骨骼装甲','EXO-49 Emancipator Exosuit','base','vehicle'],
  ['stratagem','EXO-51“伐木者”外骨骼装甲','EXO-51 Lumberer Exosuit','exo','vehicle'],
  ['stratagem','EXO-55“突破者”外骨骼装甲','EXO-55 Breakthrough Exosuit','exo','vehicle'],
  ['stratagem','M-102 快速侦察载具','M-102 Fast Recon Vehicle','base','vehicle'],
  ['stratagem','M-103 补给型快速侦察载具','M-103 Supply FRV','base','vehicle'],
  ['stratagem','TD-110“堡垒 MK XVI”坦克','TD-110 Bastion MK XVI','base','vehicle'],
  ['stratagem','MS-11 单兵导弹井','MS-11 Solo Silo','dust','offensive'],
  ['stratagem','CQC-20 破障锤','CQC-20 Breaching Hammer','base','support'],
  ['stratagem','GL-52“降级者”','GL-52 De-Escalator','law','support'],
  ['stratagem','EAT-12“纪元”','EAT-12 Epoch','control','support'],
  ['stratagem','CQC-9 落叶工具','CQC-9 Defoliation Tool','base','support'],
  ['stratagem','CQC-1 自由唯一真旗','CQC-1 One True Flag','ceremony','support'],

  // Boosters
  ['booster','地狱舱空间优化','Hellpod Space Optimization','mobilize'],
  ['booster','活力强化','Vitality Enhancement','mobilize'],
  ['booster','无人机侦察强化','UAV Recon Booster','mobilize'],
  ['booster','耐力强化','Stamina Enhancement','mobilize'],
  ['booster','肌肉强化','Muscle Enhancement','mobilize'],
  ['booster','增加增援预算','Increased Reinforcement Budget','mobilize'],
  ['booster','灵活增援预算','Flexible Reinforcement Budget','steeled'],
  ['booster','定位干扰','Localization Confusion','cutting'],
  ['booster','专家撤离飞行员','Expert Extraction Pilot','detonation'],
  ['booster','激励电击','Motivational Shocks','polar'],
  ['booster','实验性输注','Experimental Infusion','viper'],
  ['booster','火焰炸弹地狱舱','Firebomb Hellpods','flame'],
  ['booster','死亡冲刺','Dead Sprint','truth'],
  ['booster','武装补给舱','Armed Resupply Pods','urban'],
  ['booster','样本提取装置','Sample Extricator','justice'],
  ['booster','样本扫描器','Sample Scanner','ceremony'],
  ['booster','眩晕舱','Stun Pods','law'],
  ['booster','隐蔽投送','Concealed Insertion','redacted']
];

const GEAR = RAW_GEAR.map(([type,zh,en,warbond,tags=''])=>({
  id:(type+'-'+en).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),
  type,zh,en,warbond,tags:tags.split(' ').filter(Boolean)
}));

const TYPE_META = {
  primary:{zh:'主武器',icon:'◆',color:'#ffd21c'},
  secondary:{zh:'次要武器',icon:'◇',color:'#79c7ff'},
  throwable:{zh:'投掷物',icon:'●',color:'#ff8a4c'},
  stratagem:{zh:'战略配备',icon:'⬡',color:'#ef6461'},
  booster:{zh:'强化剂',icon:'✚',color:'#8cd650'}
};
